include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - custom_lint

custom_lint:
  rules:
    - riverpod_final_provider

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    use_key_in_widget_constructors: false